### ISSUE TITLE
Authorization method always return 401 code

### ISSUE THREAD

**Issue by defint** [d3xt3r2909/linkedin_login#12]
Hi.
New issue from this discussion: https://github.com/d3xt3r2909/linkedin_login/issues/11

Linkedin be able to return different errors with different codes, like 500. The error transformed here: https://github.com/d3xt3r2909/linkedin_login/blob/master/lib/src/linked_in_authorization_webview.dart#L138
On this step we have correct status code (for example 500). But result of this method uses in method `_getAccessToken`, where you override this correct code (500) to incorrect code (401, HttpStatus.unauthorized) here: https://github.com/d3xt3r2909/linkedin_login/blob/master/lib/src/linked_in_authorization_webview.dart#L97

For my opinion you should use something like:
`authorizationCode.error = tokenObject.error;`

**Comment by d3xt3r2909** [comment]
Ahh, that is it. 

Thank you @defint for good explanation. I will fix it tomorrow.

**Comment by d3xt3r2909** [comment]
@Raviteja11122 Can you also look is this case in your issue also (#11 )

**Comment by defint** [comment]
@d3xt3r2909 
I think I got caught in the middle of maintenance, was getting [500] error in the course of 1-2 hours. And spent couple of time to debug strange response status code.

By the way, thanks for your library, saved a lot of time for me.

**Comment by Raviteja11122** [comment]
@d3xt3r2909 I think so.

**Comment by d3xt3r2909** [comment]
Hello guys, 

A new version [1.1.1](https://pub.dev/packages/linkedin_login) of the package should fix this issue. Please test it if it is possible. I was trying but didn't manage to produce 500 code, so I tested it with hardcoding variables. This is [PR](https://github.com/d3xt3r2909/linkedin_login/pull/13/commits/040c92ad2b0b0fb997cf0cc0073baa1c01d6286f) for it.

@defint  Thanks once more for detail description, you helped me a lot because it is almost impossible to test something that I am not sure what is happening on your side guys. So @Raviteja11122, next time please more details and it is no problem to fix it :)

I will close ticket for now, but if the problem continue please let me know and we will reopen a ticket.

Thank you for using my library, please give me a like on [pub.dev](https://pub.dev/packages/linkedin_login).

**Comment by d3xt3r2909** [comment]
This also resolve this [issue](https://github.com/d3xt3r2909/linkedin_login/issues/11).
