### ISSUE TITLE
callback url for mobiles?

### ISSUE THREAD

**Issue by edoardoc** [d3xt3r2909/linkedin_login#28]
Hello,

followed instructions, created linkedin app and updated all the values, whenever I try to login on iOS it says:

`flutter: Error description: Scope %26quot%3Br_liteprofile%26quot%3B is not authorized for your application, Error code: 401
`

on Android:

> Webpage not available
> 
> The webpage at https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=78wh6qrif629sl&state=79a22362-122d-4a0b-98b2-dbe9cc415060&redirect_uri=https://mywebsite.com/auth/linkedin/callback&scope=r_liteprofile%20r_emailaddress could not be loaded because:
> 
> net::ERR_NAME_NOT_RESOLVED
> 

As I understand this should be able to work on mobiles also but maybe I need to set a different type of callback url?
Any help appreciated

**Comment by d3xt3r2909** [comment]
Hi, I will check this in one day probably because currently I am on a trip. 

Regarding you question, yes it should work on Android and iOS. It is still not supported, unfortunately, web and desktop because dependency which we are using has some issue.

First tip, please check did you setup everything correctly while you have created LinkedIn app on their page?

**Comment by edoardoc** [comment]
the only thing that I am not sure of is the 


`final String redirectUrl = 'https://app.carde.de';
`

which, of course I changed, and set it up both in the code and in the app definition on linkedin.
What I am not sure about is how to set up the server of this URL, usually 3 legged auth's protocols on mobile's need you to instantiate an internal server inside the app with a deep linking protocol (so no https but something like `mySmallApp://foo_bar_etc/`) that you need to code inside the Info.plist (iOS)

**Comment by d3xt3r2909** [comment]
There is nothing like to add to the redirect route, I have even use localhost. That's because everything is handled by APIs from Linkedin and there is no need to have 3 legged like on apple login. I have tried now my example and it's working. Can you also try that? 

PS: Did you set up correctly scopes for you LinkedIn app, on their site?

**Comment by edoardoc** [comment]
<img width="766" alt="Screenshot 2020-07-16 at 10 44 26" src="https://user-images.githubusercontent.com/368717/87641886-6a6c9200-c751-11ea-8829-0c84dc154925.png">


I can't edit that on their site :/

**Comment by d3xt3r2909** [comment]
You should have something like this in your **Auth** tab

![image](https://user-images.githubusercontent.com/17637299/87642703-288c1d80-c74a-11ea-9b26-a514a472c2c5.png)

**Comment by edoardoc** [comment]
yep, I got it now, thank you a lot :)

**Comment by d3xt3r2909** [comment]
I am planning soon to post an article about this, step by step. It will be easier for you guys :)

**Comment by edoardoc** [comment]
What is not really clear is what kind of permission(s) one will get choosing either of the 3 paths on dev.linkedin

Sign in with LinkedIn
Share on LinkedIn
Marketing developer platform

I need to get my list of 1st level connections, basically the people I follow on LinkedIn

**Comment by d3xt3r2909** [comment]
Hi @edoardoc  sorry for my late response. Please tag me, so that I can get a notification. I am not sure how to it because this library is just for auth, but I know that ppl had a lot of problems retrieving that information. If I remember correctly, you should apply for Marketing, and there is already a lot of feedback that they are not approving this program so easily.

**Comment by edoardoc** [comment]
:)
I applied yesterday and they rejected the application.
Future of APIs is full of applications and rejections I guess
