### ISSUE TITLE
ProfileID from r_liteprofile?

### ISSUE THREAD

**Issue by asrendon** [d3xt3r2909/linkedin_login#3]
Hello, this is not so much of a bug but rather a suggestion. I love the app but I am planning on using profileID that you can obtain with the basic r_liteprofile permission.
The profileID per person is unique to every dev SDK application and we plan on using it to manage a user's login. Would we be able to add this or do you want me to take a crack at the code and submit a pull request?
Now that the old sdk is deprecated, this plugin will come in handy for many more people.

![linkedinID](https://user-images.githubusercontent.com/8682684/56142017-edf66c80-5f6b-11e9-90d4-d89b232c4742.png)

**Comment by d3xt3r2909** [comment]
Hi, I would love to work on this feature but I am on vacation on next 2-3 weeks. So if you can and if you know feel free to create pull request.

**Comment by d3xt3r2909** [comment]
Hi, me again. 

I got some time to implement something that is OK for your case. 

So, because LinkedIn has merged some of permissions in V2 and from now on you have only three different permissions: 

> Moving forward, the available v2 APIs include:
> - r_liteprofile (replaces r_basicprofile) [included already in library]
> - r_emailaddress [included already in library]
> - w_member_social (replaces w_share) 

So, I have just expose to you user id, so from new version of this library you can access it from instance of LinkedInUserModel class (added also in example).

This is response from v2 version of https://api.linkedin.com/v2/me (r_liteprofile)

`{
    "localizedLastName": "Delic",
    "lastName": {
        "localized": {
            "en_US": "Delic"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "firstName": {
        "localized": {
            "en_US": "Nihad"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "profilePicture": {
        "displayImage": "urn:li:digitalmediaAsset:C5603AQGaIRRIo9ykpg"
    },
    "id": "clv_PXX8j9",
    "localizedFirstName": "Nihad"
}`

Anyway, one day I am planning to add permission trough parameter. But I think that your case is covered with this solution. Please confirm, so that I can close the issue.

Many thanks for opening this topic.
