### ISSUE TITLE
appBar default value ? 

### ISSUE THREAD

**Issue by NeosGamer** [d3xt3r2909/linkedin_login#31]
I used this library a few months ago and with the last version, the appBar attribute of the class "LinkedInUserWidget" has non-null check for the appBar. Could it be a better idea to add a default value (for instance: for the ones who used the library and updated it recently) or change the documentation to say it's mandatory ?

**Comment by d3xt3r2909** [comment]
Hi @NeosGamer , thanks for using a library and for opening an issue. 

The thing is that I really don't love to have `null` values inside some library. 

It's not mandatory, (it's not `@required` parameter) but you cannot forward `null value` to a parameter.  Of course, I would change this if something like this is causing an issue for you guys? 

Can you please let me know in which situation you have a problem?

**Comment by d3xt3r2909** [comment]
@NeosGamer
This should be fixed in new release of the application. So please use `linkedin_login: ^1.2.2`

Really sorry for this one, and for waiting time. Thanks for opening the issue and letting me be aware of it.

And if you didn't already please ⭐ the repo and give me a like on the pub.dev package.

Many thanks.
