### ISSUE TITLE
Getting 400 in LinkedInErrorObject on Android.

### ISSUE THREAD

**Issue by annshsingh** [d3xt3r2909/linkedin_login#32]
**Issue** - Getting **400** status code in LinkedInErrorObject whenever I am trying to login on an Android device (both emulator and physical device).
This issue is not observed on the iOS devices. 
This was working fine for both a month back.

**Relevant details** -
Flutter version - 1.22
Android version - Tested on Android 8 and 9
iOS version - iOS 14

**Comment by d3xt3r2909** [comment]
Hi, thanks for opening an issue, did you test this on an example project inside this library?

**Comment by annshsingh** [comment]
Hey @d3xt3r2909 
Thanks for getting back to me so quickly on this.

- This is what I see on the logs whenever I enter my username and password and click on Sign in inside the webview - 

`W/ContentCatcher(21093): Failed to notify a WebView 
I/flutter (21093): Error description: Failed to get token, Error code: 400`

- This is happening after I updated my Flutter to 1.22. My assumption here is that there might be some changes in the webview package or the implementation behind it that might be causing this issue.

- Example app and my code is similar, I have not made any modifications whatsoever.

I hope this helps. 
Thanks

**Comment by d3xt3r2909** [comment]
@annshsingh  

It's strange on Pixel phone it works normally, but on Samsung, it doesn't. Currently, I cannot take it so quickly need to work. But probably 2-3 days. Hope that's not too late for you. Of course, you can create PR anytime!

**Comment by d3xt3r2909** [comment]
Hi @annshsingh  again, 

I've investigated a little bit more and it seems that this bug is related, as you said already with https://pub.dev/packages/flutter_webview_plugin plugin. So, of course, I was thinking to open an issue there, but the thing is that they are planning to merge this community plugin with an official one. Please see the discussion [here](https://github.com/fluttercommunity/flutter_webview_plugin/issues/824),  of course as soon as they merge that, I will upgrade this library. 

An issue that you have reported is connected with Android operating systems 8 and 9 + new version of flutter (above 1.20), while on the latest Android OS, I've tested and it works fine.

It seems like the problem here is a little bit bigger because it's not dependent on me currently. But, I will also think about some other solution, to exclude dependency of webview totally if it's possible. 

I hope that this thing is not blocking you, and would love that someone can make fix on this topic, PR are welcome.

**Comment by d3xt3r2909** [comment]
Dear @annshsingh, 

this is so embarrassing for me haha. My example app didn't work because my WIFI connection on Samsung phone was switched off, but ppl will never stop learning from stupid mistakes. 

Ok so, I've tested on this: 

- Android 7, 8, 9 (Emulator devices) and 10, 11 (Physically  devices)
- Flutter environment: tested with `Flutter 1.23.0-18.1.pre` and `Flutter 1.20.2` 

I wasn't able to reproduce with an example project of the plugin. Please, try to use an example project, just run it. If it works, something is happening in your setup.

But based on this issue, I will create a new issue: 

- Switch from webview community  plugin to official one (they are not more in technical preview)
- Upgrade to v2 embedding

**Comment by annshsingh** [comment]
@d3xt3r2909 Hey, thanks for going so deep on the issue and coming back with some ideas on what the issue could be.
Really appreciate your time and effort here.
Apologies for a late response, I guess I missed this amongst other notifications. 

I think it is best to switch the webview here as the one currently being used is not that active anymore. 

Let me know if got time to look at this this past week.

Thanks.

**Comment by d3xt3r2909** [comment]
Hey, I will probably start working on this today and next week. 

But still, I think that problem is in your setup. Did you try to run my example?

**Comment by d3xt3r2909** [comment]
Sorry for taking me so long. It will be available soon in dev release.

**Comment by d3xt3r2909** [comment]
Hi @annshsingh,

I am working on refactoring almost everything inside the lib. (One of the changes is, of course, to switch to the new flutter web view plugin.) 

This is totally in the alpha of dev, and I do not recommend to use this in production yet, but if you want to test it, is it working with the new web view, please check this [branch](https://github.com/d3xt3r2909/linkedin_login/tree/introduce_redux)

It will take me a little bit more time to finish it,  expecting that it will be done by mid-December in the worst case.

**Comment by annshsingh** [comment]
@d3xt3r2909 Thanks a lot for looking into this issue. I will check the branch and see if the changes have any affect on the issue at hand.

**Comment by d3xt3r2909** [comment]
No problem, sorry for taking me so long. If this doesn't help, can you please then setup the example project, reproduce the same behavior, post me a link to that repo.

**Comment by d3xt3r2909** [comment]
@annshsingh Technical release is ready for this one, so if you wanna try please do and give me your feedback: 

https://pub.dev/packages/linkedin_login/versions/2.0.0-dev.1

**Comment by d3xt3r2909** [comment]
Hi @annshsingh,

is there any feedback from you? Can I close this issue?

**Comment by annshsingh** [comment]
@d3xt3r2909 Hey, I have been inactive this past week. I'll look into this over the weekend. Thank you for actively looking into this issue. Appreciate it!

**Comment by CongBaDo** [comment]
I can not login with Android device too, it redirects to redirect_url

**Comment by d3xt3r2909** [comment]
> I can not login with Android device too, it redirects to redirect_url

Hi @CongBaDo 

Please open another issue as this one is not related with your issue. Before that, please check this [comment](https://github.com/d3xt3r2909/linkedin_login/issues/37#issuecomment-734723854) or it can be same issue as [here](https://github.com/d3xt3r2909/linkedin_login/issues/25).

**Comment by d3xt3r2909** [comment]
> @d3xt3r2909 Hey, I have been inactive this past week. I'll look into this over the weekend. Thank you for actively looking into this issue. Appreciate it!

Great, let me know whenever you can
