### ISSUE TITLE
How to Use this for PWA

### ISSUE THREAD

**Issue by UmarBhutta** [d3xt3r2909/linkedin_login#44]
Hi, 
I am working on PWA where i am looking to get user login via LinkedIn.

Can you Please guide me how can i use it using this Library ?

**Comment by d3xt3r2909** [comment]
Hi @UmarBhutta, 

Please use the [readme](https://github.com/d3xt3r2909/linkedin_login/blob/master/README.md) file, [example](https://github.com/d3xt3r2909/linkedin_login/tree/master/example) project or for the current technical preview, you can use the medium article [here](https://nihad-delic91.medium.com/flutter-signin-with-linkedin-5a20f3ee11f9).

I'm closing this issue because it's not a real issue, it's more StackOverflow questions, if you don't think so, please comment it and we will open it again.

**Comment by UmarBhutta** [comment]
Hi,

I am getting below error.

MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
    at Object.throw_ [as throw] (http://localhost:61627/dart_sdk.js:5287:11)
    at MethodChannel._invokeMethod
    (http://localhost:61627/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61627/dart_sdk.js:38530:33
    at _RootZone.runUnary (http://localhost:61627/dart_sdk.js:38387:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:61627/dart_sdk.js:33377:29)
    at handleValueCallback (http://localhost:61627/dart_sdk.js:33925:49)
    at Function._propagateToListeners (http://localhost:61627/dart_sdk.js:33963:17)
    at _Future.new.[_completeWithValue] (http://localhost:61627/dart_sdk.js:33805:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61627/dart_sdk.js:33828:35)
    at Object._microtaskLoop (http://localhost:61627/dart_sdk.js:38645:13)
    at _startMicrotaskLoop (http://localhost:61627/dart_sdk.js:38651:13)
    at http://localhost:61627/dart_sdk.js:34178:9

**Comment by d3xt3r2909** [comment]
Please provide me more information on how did you get this?

- What command did you run to start an application? 
- What steps did you use to get to this?
- output of `flutter doctor --version` please

**Comment by UmarBhutta** [comment]
1.  flutter run -d chrome
2. Flutter 1.25.0-9.0.pre.42 • channel master • https://github.com/flutter/flutter.git
Framework • revision a76bb1a08e (4 days ago) • 2020-12-12 00:17:51 -0700
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)
3. I am working on Flutter Web and example project is for iOS and Android.

**Comment by d3xt3r2909** [comment]
Hi @UmarBhutta  

As you can see from www.pub.dev, unfortunately, this library is not yet supporting running applications inside your browser.  The reason for this is because the plugin for the web which should be used is not supporting this feature.

Anyhow, running the web view plugin on the web apps doesn't make sense at all, as a user can input into the search bar whatever he wants. So it's expected of web developers to handle this situation on that platform.

All that you need is to:

1. Visit link for LinkedIn auth (link should look like this, replace `XXXX` with your value):

`https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=XXXXXXX&redirect_uri=XXXXX&scope=r_liteprofile%20r_emailaddress`

2. After user input, you will get a response on your redirect URL, something like this:

`https://app.carde.de/?code=CODE_XXXXXX&state=YYYYY`

from where you should parse, and get "CODE_XXXXXX" value

3.  Then fetching access token:

`https://www.linkedin.com/oauth/v2/accessToken?grant_type=authorization_code&redirect_uri=https://www.youtube.com/callback&client_id=XXXXX&code=CODE_XXXXXX`

4. Fetch user profile

```
curl --location --request GET 'https://api.linkedin.com/v2/me?projection=(id,localizedFirstName,localizedLastName,firstName,lastName,profilePicture(displayImage~:playableStreams))' \
--header 'Authorization: Bearer Token_from_step_3
 \
--header 'Cookie: bcookie="v=coockie"; lissc=1; li_gc=secret'
```

**Comment by d3xt3r2909** [comment]
I'm closing this, as this is not meant to be a supporting feature at all.
