### ISSUE TITLE
http 0.13.0 migration

### ISSUE THREAD

**Issue by tomcajot** [d3xt3r2909/linkedin_login#46]
Package doesn't work with the latest version of http.

**Comment by d3xt3r2909** [comment]
Hi @tomcajot,

I'm planning to publish a null safety version over the weekend, where this library should work with Flutter 2.0. This will of course fix the issue which u have.

Hope that's not to late.

**Comment by tomcajot** [comment]
Thanks, that's great!

**Comment by d3xt3r2909** [comment]
Sorry, for taking so long, had a busy week.  Will be ready in day or two

**Comment by d3xt3r2909** [comment]
Hey guys,

once again, sorry for waiting a little bit longer. 

Here is a new version of the plugin: 

https://pub.dev/packages/linkedin_login/versions/2.0.0-dev.4 

Supports: 

- HTTP 0.13.0
- test coverage
- sound null safety
- logs

There are two breaking changes because: 

- New error log messaging
- And types for the profile are changed but it's no big deal to replace them

To install, please use this inside .yaml file:

` linkedin_login: ^2.0.0-dev.4`

Please report me anything which you think that's not working, as there are some big changes behind the scene, especially because of null safety. 

Thanks for reporting an issue

**Comment by tomcajot** [comment]
Thanks, will report issues if I find some.

**Comment by d3xt3r2909** [comment]
As it seems that there is no problems, I will close ticket. But please be free to open it again if doesn't work
