### ISSUE TITLE
How to disable open LinkedIn App after login successful

### ISSUE THREAD

**Issue by hohien** [d3xt3r2909/linkedin_login#6]
After login LinkedIn account successful, my iPhone opens the LinkedIn app
How can I disable it, can you help me?

Thanks

**Comment by hohien** [comment]
I really need this, please help me sir

**Comment by d3xt3r2909** [comment]
Sorry I didn't saw this issue earlier.

I need to test this because to be honest I didn't test library when you have LinkedIn app on iOS (on Android LinkedIn app is not opening). 

Second point is the same, didn't tested, but I will today, thanks for opening issue.

**Comment by d3xt3r2909** [comment]
Also, if it is not problem for you, can you open two separate issues :) 

Thanks

**Comment by hohien** [comment]
Thanks, I'm waiting for your update

**Comment by d3xt3r2909** [comment]
@hohien please check this [issue](https://github.com/d3xt3r2909/linkedin_login/issues/7) for your second question

**Comment by d3xt3r2909** [comment]
Hi @hohien , I have tried to reproduce this behavior on iOS mobile device that has installed LinkedIn app but it is working fine (without opening external app).

Did you try with example project of this library?

**Comment by hohien** [comment]
@d3xt3r2909  Oh, I have tried your example project. It works perfectly. Maybe that's my mistake 
when I code
Anyway, Thanks so much for helping me

**Comment by hohien** [comment]
@d3xt3r2909 , I have found my mistake, that's REDIRECT_URL = "https://linkedin.com"
.It shouldn't be that URL, if I change to another URL (change on linkedin developer website)

**Comment by d3xt3r2909** [comment]
Hello @hohien, would recommend that you put "Local host" address or something like that to redirect URL. 

Also maybe your app is opening because you have somewhere in your code deep links enabled for LinkedIN? 

Anyway, I am glad that you have menage to fix this issue.

**Comment by hohien** [comment]
I have a question
Is it possible if I don't set any REDIRECT_URL on LinkedIn developer website? 
Currently, I set it into https://google.com.vn
On IOS device, It works perfectly, but on Android device, after I login successfully, Webview opens google.com.vn  website

**Comment by d3xt3r2909** [comment]
1. No, it is not. Linked need this URL to return authorization code. Because of that, you need to have same value in variable "REDIRECT_URL", and on LinkedIn developer website. In, simple way, this is one way of authentification.

2. Yes, I have notice this problem and I have spend time on investigation to this. But currently, I cannot figure out how to disable this because it is behavior of webview. 

I would recommend you to: 

- Put URL that has empty page, something like http://localhost:2000/ or something similar, so that you don't have that loading of redirected page until webview don't close that widget. It would be perfect also if you can implement page just for this purpose ;) 
- Also I have notice that, when you publish real release (not debug mode) it is a little bit faster. 
- Anyway I am sorry, but I cannot do anything to fix this. You can open new ticket (but please with good description), and after webview change something in there methods this will be fixed also.

PS Thanks for feedback

**Comment by hohien** [comment]
Thanks. I got it. You are my hero ^^
