### ISSUE TITLE
Pass custom scopes instead of hardcoding in lib

### ISSUE THREAD

**Issue by georgek1991** [d3xt3r2909/linkedin_login#83]
Hi @d3xt3r2909 

Thank you for lib, this is great!

I was wondering is it possible to pass custom scopes instead of hardcoding `'&scope=r_liteprofile%20r_emailaddress'`  in the lib files.

**Comment by midhun-murali** [comment]
This is a much needed feature

**Comment by d3xt3r2909** [comment]
https://github.com/d3xt3r2909/linkedin_login/issues/63 please read about this one here, probably thats issue that you have?

**Comment by kgeorgek** [comment]
@d3xt3r2909 I have raised a PR for this issue.

**Comment by NarekManukyan** [comment]
@d3xt3r2909  I opened a PR for this #86

**Comment by d3xt3r2909** [comment]
From now on its possible, mainly thanks to @kgeorgek! 📘 

Versions from `2.3.1` are supporting it. Usage is described inside [README](https://github.com/d3xt3r2909/linkedin_login#scopes---enables-you-to-define-whatever-scope-you-are-needed). 

I am closing this issue since its resolved. Feel free to reopen/comment if you don't disagree.
