### ISSUE TITLE
Invalid Authorisation Code

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [d3xt3r2909/linkedin_login#9]
I used LinkedInAuthCodeWidget to get auth code for my app.

But when I use the the auth code to send an invitation,it says invalid code

  _sendLinkedinRequest() async {
    // set up POST request arguments
    try{
    String url = 'https://api.linkedin.com/v2/invitations';
    Map<String, String> headers = {"Content-type": "application/x-www-form-urlencoded","Authorization": "Bearer AQRjRy.....SHYCxkarv1kTR-zZw"
    };

    String json = '{"invitee": "urn:li:email:test@linkedin.com"}';
    // make POST request
    Response response = await post(url, headers: headers, body: json);
    // check the status code for the result
    int statusCode = response.statusCode;
    // this API passes back the id of the new item added to the body
    String body = response.body;
    // {
    //   "title": "Hello",
    //   "body": "body text",
    //   "userId": 1,
    //   "id": 101
    // }
    print(response.body);
    return statusCode;}
    catch(Exception){
      print(Exception);
    }
  }

error message

{"serviceErrorCode":65600,"message":"Invalid access token","status":401}

**Comment by d3xt3r2909** [comment]
Hi,

Did you try example project or?

**Comment by JERINJACOBCHERIAN** [comment]
yes I tried the example project and used the LinkedInAuthCodeWidget from it

**Comment by d3xt3r2909** [comment]
OK,

I will probably fix these on weekend. 

Thank you for understanding

**Comment by d3xt3r2909** [comment]
@JERINJACOBCHERIAN , 

I have tried right now my example project. It works on both way (profile and auth code). 

I would assume that you are using "Auth code" for access token. 

Please be aware that second tab in example project is just "Authorization code" which is needed if you want to use back-end [flow ](https://github.com/d3xt3r2909/linkedin_login/issues/5) for accessing token, otherwise, for access token, please use code on first tab to fetch AccessToken.

I will close this issue for now, but if this not fix your problem, fell free to comment it again. 

PS Sorry for my delayed response, I really didn't had time to go deep in these issues.

**Comment by d3xt3r2909** [comment]
Also, please do not forget to add permissions for your app https://stackoverflow.com/questions/50275197/linkedin-api-v2-invitations-403
